import {id,token,hash,now,text,fail,cleanHtml,passwordHash,passwordMatches,seal,safeUser,dbTools} from './shared.mjs';
import {paymentSettings,chargingEnabled,checkout,callback,checkPayment} from './payments.mjs';
import {finances,earningStatement} from './earnings.mjs';
const MAX_ARCHIVE=256*1024*1024,PART=8*1024*1024;
const contactDefault={call_center:'*006',phone:'',report_hours:2};
const catalogDefault={prices:{xray:90,usm:70,ecg:35,video:40},zones:['Bakı','Abşeron'],home_capacity:2,commission:0,report_hours:2,plan:'clinic',slots:['09:00–11:00','11:00–13:00','14:00–16:00','16:00–18:00']};
const secretFields=['api_key','secret_key','webhook_secret'];
const publicCase=c=>{const {token_hash,archive_path,...v}=c;return v;};
const plain=html=>String(html).replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim();
const doctorPublic=row=>{const {email,password,platform_id,role,...p}=safeUser(row);return {...p,specialty:'Radioloq',focus:p.focus||'Ümumi radiologiya',price:p.price||0,experience:p.experience||0,tone:0,clinic:p.clinic||'',certificates:p.certificates||[],gallery:p.gallery||[],languages:p.languages||'Azərbaycan',demo:false};};
const json=(v,status=200,headers={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store',...headers}});
export default {async fetch(request,env,ctx){
 const url=new URL(request.url),path=url.pathname;
 try{
  if(!path.startsWith('/api/'))return secure(await env.ASSETS.fetch(request),url);
  return secure(await api(request,env,url),url);
 }catch(e){if(!e.status)console.error('RADAZ API failure',e.name,e.message);return secure(json({detail:e.status?e.message:'Server əməliyyatı tamamlanmadı. Yenidən sınayın.'},e.status||500),url);}
}};
function secure(response,url){const r=new Response(response.body,response);r.headers.set('X-Content-Type-Options','nosniff');r.headers.set('Referrer-Policy','no-referrer');r.headers.set('X-Frame-Options','SAMEORIGIN');r.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'");if(url.protocol==='https:')r.headers.set('Strict-Transport-Security','max-age=31536000');return r;}
async function api(req,env,url){
 const s=dbTools(env.DB),p=url.pathname.slice(4),method=req.method,origin=env.PUBLIC_ORIGIN||url.origin;
 const viewer=()=>s.setting('viewer',{web_url:env.RADAZ_VIEWER_URL||'',desktop_enabled:false});
 if(p==='/viewer/redeem'&&method==='OPTIONS'){const v=await viewer();let allowed;try{allowed=new URL(v.web_url,origin).origin;}catch{}if(![origin,allowed].includes(req.headers.get('Origin')))throw fail(403,'Viewer mənbəyinə icazə verilmir.');return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':req.headers.get('Origin'),'Access-Control-Allow-Headers':'Content-Type, X-RADAZ-CLIENT','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}});}
 if(!['GET','HEAD'].includes(method)&&!['/viewer/redeem','/payments/callback'].includes(p))if(req.headers.get('Origin')!==origin||req.headers.get('X-RADAZ-CLIENT')!=='web')throw fail(403,'Sorğunun mənbəyi təsdiqlənmədi.');
 const cookie=(req.headers.get('Cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('radaz_session='))?.slice(14),digest=cookie?hash(cookie):'';
 let user=cookie?safeUser(await s.first('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.digest=? AND sessions.expires>?',digest,Date.now())):null;
 const auth=(...roles)=>{if(!user)throw fail(401,'Əvvəlcə hesabınıza daxil olun.');if(roles.length&&!roles.includes(user.role))throw fail(403,'Bu bölməyə girişiniz yoxdur.');return user;};
 const owner=()=>auth('admin');
 const doctor=()=>{auth('doctor','admin');if(!user.approved)throw fail(403,'Radioloq qeydiyyatınızı administrator təsdiqləməlidir.');};
 const userRow=uid=>s.first('SELECT * FROM users WHERE id=?',uid);
 const body=async()=>{if(Number(req.headers.get('Content-Length')||0)>200000)throw fail(413,'Sorğu çox böyükdür.');try{return await req.json();}catch{throw fail(400,'Sorğu oxunmadı.');}};
 async function limit(key,max=20,seconds=900){const t=Date.now(),k=key+':'+(req.headers.get('CF-Connecting-IP')||'local');await s.run('INSERT INTO rate_limits VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END',k,t+seconds*1000,t,t);if((await s.first('SELECT count FROM rate_limits WHERE key=?',k)).count>max)throw fail(429,'Sorğu limiti aşılıb. Bir qədər sonra sınayın.');}
 async function session(uid){const value=token();await s.run('INSERT INTO sessions VALUES(?,?,?)',hash(value),uid,Date.now()+8*3600000);return {'Set-Cookie':`radaz_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${url.protocol==='https:'?'; Secure':''}`};}
 async function caseFor(cid){auth();const c=await s.get(cid,'case');if(!c||!(user.role==='admin'||user.role==='doctor'&&user.approved&&c.doctor_id===user.id&&c.payment_status!=='awaiting_payment'||c.user_id===user.id))throw fail(403,'Müraciətə giriş yoxdur.');return c;}
 async function available(slot){const row=await s.first('SELECT COUNT(*) AS count FROM bookings WHERE slot_id=? AND expires>?',slot.id,Date.now());return {...slot,remaining:Math.max(0,slot.capacity-row.count)};}
 const finance=await finances({s,p,method,url,user,auth,owner,body});if(finance!==undefined)return json(finance);
 if(p==='/health')return json({ok:!!await s.first('SELECT 1 AS ok'),storage:'d1-r2'});
 if(p==='/config'){const v=await viewer(),pay=await paymentSettings(s,env);return json({radaz:true,demo_mode:false,production:true,storage:'r2',viewer_path:v.web_url,desktop_enabled:v.desktop_enabled,owner_initialized:!!env.OWNER_PLATFORM_ID,owner_login:env.TRUST_SITES_IDENTITY==='true',payments_enabled:chargingEnabled(pay),contact:await s.setting('contact',contactDefault)});}
 if(p==='/auth/identity'&&method==='GET')return json({id:req.headers.get('oai-authenticated-user-id')||null,email:req.headers.get('oai-authenticated-user-email')||null});
 if(p==='/auth/me')return json({user});
 if(p==='/auth/owner'&&method==='POST'){
  const platform=req.headers.get('oai-authenticated-user-id');if(env.TRUST_SITES_IDENTITY!=='true'||!env.OWNER_PLATFORM_ID||platform!==env.OWNER_PLATFORM_ID)throw fail(403,'Bu giriş yalnız sayt sahibinin təsdiqlənmiş hesabına aiddir.');
  let row=await s.first('SELECT * FROM users WHERE platform_id=?',platform);
  if(!row){let name=req.headers.get('oai-authenticated-user-full-name')||'Sayt administratoru';if(req.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')try{name=decodeURIComponent(name);}catch{}
   const uid=id('owner'),email=String(req.headers.get('oai-authenticated-user-email')||'owner@radaz.local').toLowerCase();
   await s.run("INSERT INTO users(id,email,role,approved,profile,platform_id,created_at) VALUES(?,?,'admin',1,?,?,?)",uid,email,JSON.stringify({name}),platform,now());row=await userRow(uid);
  }return json({user:safeUser(row)},200,await session(row.id));
 }
 if(p==='/auth/register'&&method==='POST'){
  await limit('register',10,3600);const d=await body(),email=text(d.email).toLowerCase(),password=String(d.password||''),name=text(d.name),role=d.role;
  if(!['patient','doctor','clinic'].includes(role)||!/^\S+@\S+\.\S+$/.test(email)||password.length<12||password.length>1024||!name)throw fail(400,'Ad, düzgün email, hesab növü və ən az 12 simvolluq şifrə daxil edin.');
  if(email===env.OWNER_EMAIL?.toLowerCase())throw fail(409,'Sayt sahibi üçün “Administrator girişi” düyməsindən istifadə edin.');
  if(await s.first('SELECT id FROM users WHERE email=?',email))throw fail(409,'Bu email ilə qeydiyyat mövcuddur. Giriş səhifəsindən daxil olun.');
  const uid=id('user');await s.run('INSERT INTO users(id,email,password,role,approved,profile,created_at) VALUES(?,?,?,?,?,?,?)',uid,email,await passwordHash(password),role,role==='patient'?1:0,JSON.stringify({name,clinic:text(d.clinic)}),now());return json({user:safeUser(await userRow(uid))},201,await session(uid));
 }
 if(p==='/auth/login'&&method==='POST'){await limit('login',15);const d=await body(),pw=String(d.password||'');if(pw.length>1024)throw fail(400,'Giriş məlumatları düzgün deyil.');const row=await s.first('SELECT * FROM users WHERE email=?',text(d.email).toLowerCase());if(!await passwordMatches(pw,row?.password))throw fail(401,'Email və ya şifrə düzgün deyil. Hesabınız yoxdursa, qeydiyyatdan keçin.');return json({user:safeUser(row)},200,await session(row.id));}
 if(p==='/auth/logout'&&method==='POST'){if(digest)await s.run('DELETE FROM sessions WHERE digest=?',digest);return json({ok:true},200,{'Set-Cookie':'radaz_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0; Secure'});}
 if(p==='/doctors')return json((await s.all("SELECT * FROM users WHERE role IN ('doctor','admin') AND approved=1 AND CAST(json_extract(profile,'$.price') AS REAL)>0")).map(doctorPublic));
 if(p==='/slots'){const rows=await s.records('slot'),out=[];for(const sl of rows)if(sl.date===url.searchParams.get('date')&&(await userRow(sl.doctor_id))?.approved)out.push(await available(sl));return json(out);}
 if(p==='/me/profile'){auth();if(method==='PUT'){const d=await body(),old=JSON.parse((await userRow(user.id)).profile);for(const k of ['name','focus','clinic','about','education','courses','languages','phone'])if(k in d)old[k]=text(d[k],k==='about'?10000:1000);for(const k of ['price','experience'])if(k in d){const n=Number(d[k]);if(!Number.isFinite(n)||n<0||n>10000)throw fail(400,'Rəqəm düzgün deyil.');old[k]=n;}for(const k of ['avatar','certificates','gallery'])if(k in d){const list=k==='avatar'?(d[k]?[{url:d[k]}]:[]):d[k];if(!Array.isArray(list)||list.length>30)throw fail(400,'Profil faylları düzgün deyil.');const checked=[];for(const item of list){const mid=String(item.url||'').match(/^\/api\/media\/(media-[a-f0-9]+)$/)?.[1],m=mid?await s.get(mid,'media'):null;if(!m||m.owner!==user.id||m.kind!==(k==='avatar'?'avatar':k==='certificates'?'certificate':'gallery'))throw fail(400,'Profil faylı sizə aid deyil.');checked.push({id:m.id,url:'/api/media/'+m.id,name:m.name,kind:m.kind});}old[k]=k==='avatar'?(checked[0]?.url||''):checked;}await s.run('UPDATE users SET profile=? WHERE id=?',JSON.stringify(old),user.id);}return json({...doctorPublic(await userRow(user.id)),email:user.email});}
 if(p==='/me/availability'){auth('doctor','admin');if(method==='POST'){doctor();const d=await body();if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!/^\d{2}:\d{2}–\d{2}:\d{2}$/.test(d.time)||!Number.isInteger(d.capacity)||d.capacity<1||d.capacity>100)throw fail(400,'Qəbul intervalı düzgün deyil.');if((await s.records('slot',user.id)).some(sl=>sl.date===d.date&&sl.time===d.time))throw fail(409,'Bu interval mövcuddur.');return json(await s.put('slot',user.id,{id:id('slot'),doctor_id:user.id,date:d.date,time:d.time,capacity:d.capacity}),201);}return json(await Promise.all((await s.records('slot',user.id)).map(available)));}
 if(p.startsWith('/me/availability/')&&method==='DELETE'){doctor();const sl=await s.get(p.split('/').at(-1),'slot');if(sl?.doctor_id!==user.id)throw fail(404,'Interval tapılmadı.');if((await available(sl)).remaining<sl.capacity)throw fail(409,'Müraciəti olan interval silinə bilməz.');await s.run("DELETE FROM records WHERE id=? AND kind='slot'",sl.id);return json({ok:true});}
 if(p.startsWith('/admin/')){
  owner();
  if(p==='/admin/pending')return json({doctors:(await s.all("SELECT * FROM users WHERE role='doctor' AND approved=0")).map(doctorPublic),clinics:(await s.records('clinic')).filter(c=>c.status==='pending')});
  if(p==='/admin/approve'&&method==='POST'){const d=await body();if(d.kind==='doctor')await s.run("UPDATE users SET approved=1 WHERE id=? AND role='doctor'",text(d.id));else if(d.kind==='clinic'){const c=await s.get(d.id,'clinic');if(!c)throw fail(404,'Klinika tapılmadı.');await s.put('clinic',c.owner_id,{...c,status:'approved'});}else throw fail(400,'Növ düzgün deyil.');return json({ok:true});}
  if(p==='/admin/site-settings'){if(method==='PUT'){const d=await body();if(!/^[+*\d\s()#-]{2,30}$/.test(d.call_center||'')||(d.phone&&!/^[+\d\s()-]{5,40}$/.test(d.phone)))throw fail(400,'Əlaqə nömrəsi düzgün deyil.');await s.set('contact',{call_center:text(d.call_center,30),phone:text(d.phone,40),report_hours:2});}return json(await s.setting('contact',contactDefault));}
  if(p==='/admin/viewer-settings'){if(method==='PUT'){const d=await body(),raw=text(d.web_url,2000);let v;try{v=raw?new URL(raw,origin):null;}catch{throw fail(400,'RADAZ ünvanı düzgün deyil.');}if(v&&(!['http:','https:'].includes(v.protocol)||v.username||v.password||v.hash||v.search||(v.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(v.hostname))))throw fail(400,'HTTPS və ya lokal RADAZ ünvanı daxil edin.');await s.set('viewer',{web_url:v?.href||'',desktop_enabled:d.desktop_enabled===true});}return json(await viewer());}
  if(p==='/admin/payment-settings'){
   let v=await paymentSettings(s,env);if(method==='PUT'){const d=await body();for(const k of ['provider','environment','merchant_id','bank_name','account_holder','iban','swift','tax_id','currency','notes'])if(k in d)v[k]=text(d[k],k==='notes'?2000:300);if(!['unconfigured','bank_transfer','epoint','other'].includes(v.provider)||!['test','live'].includes(v.environment)||!['AZN','USD','EUR'].includes(v.currency))throw fail(400,'Ödəniş parametrləri düzgün deyil.');for(const k of secretFields)if(d.clear_secrets?.includes(k))delete v[k];else if(d[k]?.trim())v[k]=text(d[k],4096);if(v.environment==='live'&&!chargingEnabled(v))throw fail(400,'Canlı kart ödənişi üçün Epoint, AZN, Merchant public key və Secret key tələb olunur. Bank rekvizitləri təkbaşına kart ödənişini aktiv etmir.');v.updated_at=now();await s.set('payment',await seal(env.SETTINGS_ENCRYPTION_KEY,v));await s.audit(user.id,'payment_settings_updated');}
   const secrets=Object.fromEntries(secretFields.map(k=>[k,!!v[k]])),enabled=chargingEnabled(v);for(const k of secretFields)delete v[k];return json({values:v,secrets,configured:!!v.provider,charging_enabled:enabled});
  }
 }
 if(p==='/me/media'&&method==='POST'){
  auth('doctor','admin');await limit('profile-upload',25,3600);const length=Number(req.headers.get('Content-Length')||0);if(length<1||length>9*1024*1024)throw fail(413,'Fayl 8 MB-dan böyükdür.');
  const form=await req.formData(),file=form.get('file'),kind=String(form.get('kind'));if(!(file instanceof File)||file.size>8*1024*1024||!['avatar','certificate','gallery'].includes(kind))throw fail(400,'Profil faylı düzgün deyil.');
  const bytes=new Uint8Array(await file.arrayBuffer()),jpeg=bytes[0]===255&&bytes[1]===216,png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,pdf=new TextDecoder().decode(bytes.slice(0,5))==='%PDF-',webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';
  const mime=jpeg?'image/jpeg':png?'image/png':webp?'image/webp':pdf&&kind==='certificate'?'application/pdf':null;if(!mime)throw fail(400,'JPG, PNG, WEBP və ya sertifikat üçün PDF seçin.');
  const mid=id('media'),key='profiles/'+mid;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});const m={id:mid,owner:user.id,kind,name:text(file.name,150),mime,key,created_at:now()};await s.put('media',user.id,m);return json({id:mid,url:'/api/media/'+mid,name:m.name,kind},201);
 }
 if(p.startsWith('/media/')){
  const m=await s.get(p.split('/')[2],'media');if(!m)throw fail(404,'Fayl tapılmadı.');const row=await userRow(m.owner),profile=JSON.parse(row?.profile||'{}');const isPublic=row?.approved&&(profile.avatar==='/api/media/'+m.id||[...(profile.certificates||[]),...(profile.gallery||[])].some(x=>x.id===m.id));if(!isPublic&&user?.id!==m.owner&&user?.role!=='admin')throw fail(403,'Fayla giriş yoxdur.');const file=await env.BUCKET.get(m.key);if(!file)throw fail(404,'Fayl tapılmadı.');return new Response(file.body,{headers:{'Content-Type':m.mime,'Cache-Control':'private, max-age=300',...(m.mime==='application/pdf'?{'Content-Disposition':'attachment; filename="certificate.pdf"'}:{})}});
 }
 if(p==='/uploads'&&method==='POST'){
  auth();await limit('upload',12,3600);const d=await body();if(!Number.isInteger(d.size)||d.size<4||d.size>MAX_ARCHIVE)throw fail(400,'4 bayt–256 MB ZIP arxivi seçin.');const uid=id('upload'),key='archives/'+uid+'.zip',m=await env.BUCKET.createMultipartUpload(key,{httpMetadata:{contentType:'application/zip'}});await s.run('INSERT INTO uploads VALUES(?,?,?,?,?,?)',uid,user.id,key,d.size,Date.now()+3600000,JSON.stringify({phase:'uploading',uploadId:m.uploadId,parts:[]}));return json({id:uid,part_size:PART},201);
 }
 if(p.startsWith('/uploads/')){
  auth();const bits=p.split('/'),u=await s.first('SELECT * FROM uploads WHERE id=? AND owner=? AND expires>?',bits[2],user.id,Date.now());if(!u)throw fail(404,'Yükləmə tapılmadı və ya vaxtı bitib.');const st=JSON.parse(u.state);if(st.phase!=='uploading')throw fail(409,'Yükləmə artıq tamamlanıb.');const m=env.BUCKET.resumeMultipartUpload(u.object_key,st.uploadId);
  if(bits[3]==='parts'&&method==='PUT'){const part=Number(bits[4]),count=Math.ceil(u.size/PART),expected=part===count?u.size-PART*(count-1):PART;if(!Number.isInteger(part)||part<1||part>count||Number(req.headers.get('Content-Length'))!==expected)throw fail(400,'Arxiv hissəsinin ölçüsü düzgün deyil.');const result=await m.uploadPart(part,req.body);st.parts=st.parts.filter(q=>q.partNumber!==part);st.parts.push(result);await s.run('UPDATE uploads SET state=? WHERE id=?',JSON.stringify(st),u.id);return json({ok:true});}
  if(bits[3]==='complete'&&method==='POST'){if(st.parts.length!==Math.ceil(u.size/PART))throw fail(400,'Arxivin hissələri tamamlanmayıb.');await m.complete(st.parts.sort((a,b)=>a.partNumber-b.partNumber));const head=await env.BUCKET.get(u.object_key,{range:{offset:0,length:4}}),signature=new Uint8Array(await head.arrayBuffer());if(signature[0]!==80||signature[1]!==75){await env.BUCKET.delete(u.object_key);await s.run('DELETE FROM uploads WHERE id=?',u.id);throw fail(400,'ZIP arxivi seçin.');}await s.run('UPDATE uploads SET state=? WHERE id=?',JSON.stringify({phase:'complete'}),u.id);return json({id:u.id});}
 }
 if(p==='/consultations'&&method==='POST'){
  auth();await limit('consultation',12,3600);const d=await body(),patient=d.patient||{},u=await s.first('SELECT * FROM uploads WHERE id=? AND owner=? AND expires>?',text(d.archive_id),user.id,Date.now());
  if(!d.consent||!text(patient.first_name)||!text(patient.last_name)||!/^\S+@\S+\.\S+$/.test(patient.email||'')||!text(patient.phone)||!text(patient.complaints))throw fail(400,'Pasiyent məlumatlarını və razılığı tamamlayın.');
  if(!u||JSON.parse(u.state).phase!=='complete')throw fail(400,'Əvvəlcə DICOM ZIP arxivini yükləyin.');
  const sl=await s.get(d.slot_id,'slot'),dr=await userRow(d.doctor_id);if(!sl||sl.doctor_id!==d.doctor_id||!dr?.approved)throw fail(409,'Seçilmiş vaxt mövcud deyil.');
  const cid=id('RZ'),receipt=token(),enabled=chargingEnabled(await paymentSettings(s,env));
  const c={id:cid,user_id:user.id,doctor_id:dr.id,slot_id:sl.id,patient:Object.fromEntries(['first_name','last_name','father_name','birth_date','email','phone','complaints','language','report_language'].map(k=>[k,text(patient[k],k==='complaints'?10000:250)])),report_date:sl.date,time:sl.time,price:JSON.parse(dr.profile).price||0,status:enabled?'awaiting_payment':'pending',payment_status:enabled?'awaiting_payment':'demo',sample:false,created_at:now(),response_due_at:enabled?null:new Date(Date.now()+7200000).toISOString(),archive_path:u.object_key,file_name:cid+'.zip',file_size:u.size,token_hash:hash(receipt),report:'',version:0,metadata:{modality:text(d.metadata?.modality,20),patient_id:text(d.metadata?.patient_id,100),dicom_count:Number(d.metadata?.dicom_count)||0}};
  const results=await s.db.batch([
   s.db.prepare('INSERT INTO bookings SELECT ?,?,?,? WHERE (SELECT COUNT(*) FROM bookings WHERE slot_id=? AND expires>?)<? AND EXISTS(SELECT 1 FROM uploads WHERE id=? AND state=?)').bind(cid,sl.id,cid,8640000000000000,sl.id,Date.now(),sl.capacity,u.id,u.state),
   s.db.prepare("UPDATE uploads SET state='{"+'"phase":"used"'+"}' WHERE id=? AND EXISTS(SELECT 1 FROM bookings WHERE id=?)").bind(u.id,cid),
   s.db.prepare('INSERT INTO records SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=?)').bind(cid,'case',dr.id,JSON.stringify(c),c.created_at,cid)
  ]);
  if(!results[0].meta.changes)throw fail(409,'Seçilmiş vaxt dolub və ya arxiv artıq istifadə edilib.');
  return json({case:publicCase(c),token:receipt},201);
 }
 if(p==='/me/cases'){auth();const cases=await s.records('case');return json(cases.filter(c=>user.role==='admin'||c.user_id===user.id||(user.approved&&c.doctor_id===user.id&&c.payment_status!=='awaiting_payment')).map(c=>publicCase(user.role==='patient'&&!['approved','sent'].includes(c.status)?{...c,report:''}:c)));}
 if(p.startsWith('/cases/')){
  const [, ,cid,action]=p.split('/'),c=await caseFor(cid);
  if(!action)return json(publicCase(user.role==='patient'&&!['approved','sent'].includes(c.status)?{...c,report:''}:c));
  if(action==='report'&&method==='PUT'){doctor();if(c.doctor_id!==user.id&&user.role!=='admin')throw fail(403,'Müraciət sizə təyin olunmayıb.');const d=await body();if(['approved','sent','awaiting_payment'].includes(c.status))throw fail(409,'Hesabat hazırda redaktə edilə bilməz.');if(d.version!==c.version)throw fail(409,'Hesabat başqa pəncərədə dəyişib. Yeniləyin.');const html=cleanHtml(d.html);if(d.approve&&!plain(html))throw fail(400,'Boş hesabat təsdiqlənə bilməz.');const next={...c,report:html,version:c.version+1,status:d.approve?'approved':'in_review',...(d.approve?{approved_at:now()}:{})};const statement=s.db.prepare("UPDATE records SET value=? WHERE id=? AND json_extract(value,'$.version')=? AND json_extract(value,'$.status') NOT IN ('approved','sent','awaiting_payment')").bind(JSON.stringify(next),cid,d.version),earning=d.approve?await earningStatement(s,next):null;const [changed]=await s.db.batch([statement,...(earning?[earning]:[])]);if(!changed.meta.changes)throw fail(409,'Hesabat başqa pəncərədə dəyişib. Yeniləyin.');await s.put('version',cid,{id:id('version'),case_id:cid,version:next.version,html,status:next.status,created_at:now()});return json(publicCase(next));}
  if(action==='archive'){const obj=await env.BUCKET.get(c.archive_path);if(!obj)throw fail(404,'Arxiv tapılmadı.');return new Response(obj.body,{headers:{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${c.file_name}"`,'Cache-Control':'no-store'}});}
  if(action==='viewer-launch'&&method==='POST'){doctor();const v=await viewer();if(!v.web_url)throw fail(409,'Administrator RADAZ ünvanını hələ qoşmayıb.');const grant=token(),target=new URL(v.web_url,origin);await s.run('INSERT INTO launches VALUES(?,?,?,?,?)',hash(grant),cid,user.id,target.origin,Date.now()+120000);target.hash=new URLSearchParams({'radaz-site':origin,'radaz-ticket':grant}).toString();return json({url:target.href,desktop_url:v.desktop_enabled?'radaz://open?'+new URLSearchParams({url:target.href}):null,expires_in:120});}
  if(action==='checkout'&&method==='POST'){if(c.user_id!==user.id&&user.role!=='admin')throw fail(403,'Ödənişə giriş yoxdur.');if(c.payment_status!=='awaiting_payment')throw fail(409,'Bu müraciət ödəniş gözləmir.');return json(await checkout(s,env,c,origin));}
  if(action==='payment-status'){const payment=await s.first('SELECT * FROM payments WHERE case_id=? ORDER BY created_at DESC LIMIT 1',cid);if(!payment)return json({state:c.payment_status});return json(await checkPayment(s,env,payment));}
 }
 if(p==='/viewer/redeem'&&method==='POST'){await limit('redeem',60);const d=await body(),g=await s.first('SELECT * FROM launches WHERE digest=? AND expires>?',hash(d.ticket||''),Date.now());if(!g||![g.origin,origin].includes(req.headers.get('Origin')))throw fail(403,'Viewer keçidi etibarsızdır və ya vaxtı bitib.');const c=await s.get(g.case_id,'case'),row=await userRow(g.user_id);if(!row?.approved||!(row.role==='admin'||c?.doctor_id===row.id))throw fail(403,'Müraciətə giriş yoxdur.');const r=await s.run('DELETE FROM launches WHERE digest=?',g.digest);if(!r.meta.changes)throw fail(403,'Keçid artıq istifadə olunub.');const file=await env.BUCKET.get(c.archive_path);if(!file)throw fail(404,'Arxiv tapılmadı.');return new Response(file.body,{headers:{'Content-Type':'application/zip','Access-Control-Allow-Origin':req.headers.get('Origin'),'Vary':'Origin','Cache-Control':'no-store'}});}
 if(p==='/payments/callback'&&method==='POST')return json(await callback(req,s,env));
 if(p==='/tracking'&&method==='POST'){await limit('tracking',40);const d=await body(),c=await s.get(text(d.id),'case');if(!c||hash(d.token||'')!==c.token_hash)throw fail(404,'Müraciət kodu və ya giriş açarı yanlışdır.');return json({...publicCase(c),report:['approved','sent'].includes(c.status)?c.report:''});}
 if(p==='/me/notifications'){auth();return json([]);}
 if(p==='/me/clinics'){auth();return json(await s.records('clinic',user.id));}
 if(p==='/clinics'&&method==='POST'){auth('clinic','doctor','admin');const d=await body();if(!text(d.name))throw fail(400,'Klinika adını daxil edin.');return json(await s.put('clinic',user.id,{id:id('clinic'),owner_id:user.id,name:text(d.name),address:text(d.address),phone:text(d.phone),status:'pending',connection:'not_configured'}),201);}
 if(p==='/x/catalog')return json(await s.setting('catalog',catalogDefault));
 if(p==='/x/settings'&&method==='PUT'){owner();const d=await body();if(!d.prices||!Array.isArray(d.zones)||d.zones.length>30||Object.values(d.prices).some(n=>!Number.isFinite(n)||n<0||n>10000))throw fail(400,'Qiymətlər və zonalar düzgün deyil.');const value={...catalogDefault,...d,report_hours:2};await s.set('catalog',value);return json(value);}
 if(p.startsWith('/x/templates')){doctor();const tid=p.split('/')[3];if(method==='GET')return json(await s.records('template',user.id));if(method==='DELETE'){const r=await s.run("DELETE FROM records WHERE id=? AND kind='template' AND owner=?",tid,user.id);if(!r.meta.changes)throw fail(404,'Şablon tapılmadı.');return json({ok:true});}if(['POST','PUT'].includes(method)){const d=await body(),old=tid?await s.get(tid,'template'):null;if(tid&&old?.owner!==user.id)throw fail(404,'Şablon tapılmadı.');if(!text(d.title)||!['CT','MR','CR','US'].includes(d.modality)||!['az','ru','en'].includes(d.lang)||!plain(d.html))throw fail(400,'Şablonun adını, qrupunu, dilini və mətnini daxil edin.');return json(await s.put('template',user.id,{id:old?.id||id('template'),owner:user.id,title:text(d.title,150),modality:d.modality,lang:d.lang,html:cleanHtml(d.html),created_at:old?.created_at||now(),updated_at:now()}));}}
 if(p==='/x/security'){auth();return json({enabled:false,sessions:(await s.all('SELECT digest,expires FROM sessions WHERE user_id=? AND expires>?',user.id,Date.now())).map(v=>({id:v.digest.slice(0,16),current:v.digest===digest,expires_at:new Date(v.expires).toISOString()}))});}
 if(p.startsWith('/x/cases/')){const c=await caseFor(p.split('/')[3]);return json({messages:await s.records('message',c.id),versions:user.role==='patient'?[]:await s.records('version',c.id),addenda:[],critical:[],reviews:[],events:[],attachments:[],role:user.role,case_status:c.status});}
 if(p.startsWith('/x/messages/')&&method==='POST'){const c=await caseFor(p.split('/')[3]),d=await body();if(!text(d.text))throw fail(400,'Mesaj yazın.');return json(await s.put('message',c.id,{id:id('message'),author:user.name,actor:user.id,text:text(d.text,6000),created_at:now()}));}
 if(p==='/x/operations'){auth('doctor','admin');return json({orders:[],cases:(await s.records('case')).filter(c=>user.role==='admin'||c.doctor_id===user.id&&user.approved).map(publicCase),critical:[],reviews:[],teams:[],waitlist:[],refunds:[],settings:await s.setting('catalog',catalogDefault),audit:user.role==='admin'?await s.all('SELECT actor,action,target AS case_id,at FROM audit ORDER BY id DESC LIMIT 200'):[]});}
 if(p==='/x/slots')return json([]);
 throw fail(404,'Bu xidmət mövcud deyil.');
}
